### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by Shortowsky** [Keithenneu/Beowulf.ArmaTerrainExport#1]
Hello, i tried the code and got a really long loading time, but i did not get a .png file as expected. Can you help me set it up please?

**Comment by Keithenneu** [comment]
I've updated the readme to contain the steps needed to run everything.
I suppose I could make it all a bit more user friendly, if there's interest.

**Comment by Shortowsky** [comment]
Hey, Thank you very much, but i have to admit that my scripting knowledge doesn't exceed ArmA's sqf.
Is there a possibility you could help me get this trough babystep by babystep, or even do this for me, as you might already have set up all programs and libraries needed? I dont expect this from you, but would be really nice. I am currently planning on a total rework of a popular early ArmA Map, kinda like BI redid Malden...

**Comment by Keithenneu** [comment]
haha, yeah, guess I can do that for you. which map is it?

**Comment by Shortowsky** [comment]
Oh, this would be soo nice of you :+1: 
The Map is Sahrani, and i promise you to mention you in the project when it gets published.
Or maybe there will be a Easter Egg somewhere ;)

**Comment by Keithenneu** [comment]
got CUP loaded and Sahrani, United Sahrani and Souther Sahrani. Which one do you want? (I think there's no difference between sharani and united. just double checking)

**Comment by Shortowsky** [comment]
The normal Sahrani and United Sahrani only differ in the objects, not in the Terrain, and Southern Sahrani is, as guessed only the southern Part, so "Sahrani" please :)

**Comment by Keithenneu** [comment]
ok. will do it after tonights op.

**Comment by Keithenneu** [comment]
there you go: https://www.dropbox.com/s/9e1038gotke39tf/terrain.png?dl=1

**Comment by Shortowsky** [comment]
Oh, thank you, thank you very much.
If i can ever do you a favour within the range of my possibilities, just let me know :call_me_hand: 
I wish you the best of luck and fun in your future operations :)
